name       : python-waitress
version    : 2.1.2
release    : 7
source     :
    - https://github.com/Pylons/waitress/archive/v2.1.2.tar.gz : 2de9b24b8097c82535aa6f512d9c93096c51affd22cb640342c21761a5b38873
license    : ZPL-2.1
component  : programming.python
summary    : A WSGI server for Python
description: |
    Waitress is meant to be a production-quality pure-Python WSGI server with very acceptable performance. It supports HTTP/1.0 and HTTP/1.1.
builddeps  :
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
