name       : python-waitress
version    : 1.4.4
release    : 1
source     :
    - https://github.com/Pylons/waitress/archive/v1.4.4.tar.gz : 857d94a0f87954bceb954c8685c94565eb59ac5a81229ba252e2f86dab182d6d
license    : ZPL-2.1
component  : programming.python
summary    : A WSGI server for Python 2 and 3
description: |
    Waitress is meant to be a production-quality pure-Python WSGI server with very acceptable performance. It supports HTTP/1.0 and HTTP/1.1.
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
