name       : python-waitress
version    : 2.1.0
release    : 4
source     :
    - https://github.com/Pylons/waitress/archive/v2.1.0.tar.gz : be71ddee758713b6fab6396aca48eca290eef59b0e5b28e3406609674556d114
license    : ZPL-2.1
component  : programming.python
summary    : A WSGI server for Python
description: |
    Waitress is meant to be a production-quality pure-Python WSGI server with very acceptable performance. It supports HTTP/1.0 and HTTP/1.1.
builddeps  :
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
