name       : python-waitress
version    : 2.0.0
release    : 2
source     :
    - https://github.com/Pylons/waitress/archive/v2.0.0.tar.gz : 1cf044f7257aab8c0935d401661a92b5cce7d27ff2abb8c528f084b6ff0c2e24
license    : ZPL-2.1
component  : programming.python
summary    : A WSGI server for Python
description: |
    Waitress is meant to be a production-quality pure-Python WSGI server with very acceptable performance. It supports HTTP/1.0 and HTTP/1.1.
builddeps  :
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
