name       : python-waitress
version    : 2.1.1
release    : 5
source     :
    - https://github.com/Pylons/waitress/archive/v2.1.1.tar.gz : bc7cd755f719035721d0aba06821e855870017df64d7e479aa6ab55efa61de1d
license    : ZPL-2.1
component  : programming.python
summary    : A WSGI server for Python
description: |
    Waitress is meant to be a production-quality pure-Python WSGI server with very acceptable performance. It supports HTTP/1.0 and HTTP/1.1.
builddeps  :
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
